"""
Born-rule diagnostics for disentanglement angle histograms.

The disentanglement analyzer produces eigenvalues of the relative
evolution operator ``M(t) = U00(t)^(-1) U10(t)``.  Older scripts also
call this matrix ``W0``.  Its eigenvalue radii satisfy

    |lambda| = tan(theta / 2),

so the same samples define both the theta histogram and its reflected
partner at ``pi - theta``.  This module keeps the numerical diagnostics
used by the search scripts in one place.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class BornRatioResult:
    """Bin-wise ratio against the Born reference curve."""

    theta_centers: np.ndarray
    ratio: np.ndarray
    born: np.ndarray
    counts_0: np.ndarray
    counts_1: np.ndarray
    similarity: float
    mean_abs_error: float


@dataclass(frozen=True)
class TailEstimate:
    """Hill estimate for a power-law radius tail."""

    density_exponent: float
    survival_exponent: float
    xmin: float
    n_tail: int


@dataclass(frozen=True)
class PhaseUniformityResult:
    """Scalar diagnostics for Bloch-sphere azimuth coverage."""

    n_samples: int
    n_bins: int
    uniformity_score: float
    entropy_score: float
    total_variation: float
    max_bin_fraction: float
    rayleigh_r: float
    bin_edges: np.ndarray
    counts: np.ndarray


@dataclass(frozen=True)
class BornDiagnostics:
    """Compact scalar diagnostics for ranking Hamiltonian candidates."""

    n_samples: int
    born_similarity: float
    mean_abs_ratio_error: float
    reciprocity_error: float
    tail_density_exponent: float
    tail_survival_exponent: float
    tail_xmin: float
    p95_radius: float
    p99_radius: float
    max_radius: float


def theta_from_z(z: np.ndarray) -> np.ndarray:
    """Map Bloch ``z`` coordinates to polar angles in ``[0, pi]``."""

    return np.arccos(np.clip(np.asarray(z, dtype=float), -1.0, 1.0))


def theta_pair_from_radii(radii: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return ``(theta, pi - theta)`` from ``|lambda|`` samples."""

    x = _clean_positive(radii, allow_zero=True)
    theta = 2.0 * np.arctan(x)
    return theta, np.pi - theta


def theta_pair_from_eigenvalues(
    eigenvalues: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Return ``(theta, pi - theta)`` from eigenvalues of ``M(t)``."""

    return theta_pair_from_radii(np.abs(np.asarray(eigenvalues)))


def phase_angles_from_eigenvalues(
    eigenvalues: np.ndarray,
    include_antipodes: bool = True,
) -> np.ndarray:
    r"""
    Return Bloch azimuths generated by eigenvalues of ``M(t)``.

    For the initial-state branch

    .. math::
        |\phi_0(\lambda)\rangle =
        \frac{|0\rangle + \lambda |1\rangle}{\sqrt{1+|\lambda|^2}},

    the azimuthal Bloch angle is ``arg(lambda)``.  The reflected branch is
    antipodal on the Bloch sphere, so its azimuth is shifted by ``pi``.
    """

    lam = np.asarray(eigenvalues, dtype=np.complex128).ravel()
    finite = np.isfinite(lam.real) & np.isfinite(lam.imag)
    lam = lam[finite]
    phases = np.mod(np.angle(lam), 2.0 * np.pi)
    if include_antipodes:
        phases = np.concatenate([phases, np.mod(phases + np.pi, 2.0 * np.pi)])
    return phases


def phase_uniformity_from_eigenvalues(
    eigenvalues: np.ndarray,
    n_phi: int = 36,
    include_antipodes: bool = True,
) -> PhaseUniformityResult:
    """
    Score whether Bloch azimuths cover ``[0, 2*pi)`` roughly uniformly.

    ``uniformity_score`` is one for a perfectly flat histogram and zero for a
    single occupied bin, using a normalized total-variation distance from the
    uniform distribution.  ``entropy_score`` is the Shannon entropy normalized
    by ``log(n_phi)``.  ``rayleigh_r`` measures first-harmonic angular
    concentration; it is reported but not used alone because antipodal clouds
    can have small first harmonic while still occupying only two azimuths.
    """

    if n_phi <= 1:
        raise ValueError("n_phi must be greater than 1")

    phases = phase_angles_from_eigenvalues(
        eigenvalues,
        include_antipodes=include_antipodes,
    )
    edges = np.linspace(0.0, 2.0 * np.pi, n_phi + 1)
    counts, _ = np.histogram(phases, bins=edges)
    n_samples = int(counts.sum())
    if n_samples == 0:
        return PhaseUniformityResult(
            n_samples=0,
            n_bins=int(n_phi),
            uniformity_score=np.nan,
            entropy_score=np.nan,
            total_variation=np.nan,
            max_bin_fraction=np.nan,
            rayleigh_r=np.nan,
            bin_edges=edges,
            counts=counts,
        )

    probabilities = counts.astype(float) / n_samples
    uniform = np.full(n_phi, 1.0 / n_phi)
    total_variation = 0.5 * float(np.sum(np.abs(probabilities - uniform)))
    max_tv = 1.0 - 1.0 / n_phi
    uniformity_score = max(0.0, 1.0 - total_variation / max_tv)

    occupied = probabilities[probabilities > 0.0]
    entropy = -float(np.sum(occupied * np.log(occupied)))
    entropy_score = entropy / np.log(n_phi)
    rayleigh_r = float(np.abs(np.mean(np.exp(1j * phases))))

    return PhaseUniformityResult(
        n_samples=n_samples,
        n_bins=int(n_phi),
        uniformity_score=float(uniformity_score),
        entropy_score=float(entropy_score),
        total_variation=total_variation,
        max_bin_fraction=float(np.max(probabilities)),
        rayleigh_r=rayleigh_r,
        bin_edges=edges,
        counts=counts,
    )


def born_ratio_from_theta(
    theta0: np.ndarray,
    theta1: np.ndarray,
    n_theta: int = 100,
    empty_value: float = 0.5,
    pseudocount: float = 0.0,
) -> BornRatioResult:
    r"""
    Compute ``P(theta) / (P(theta) + P(pi - theta))`` on theta bins.

    The similarity score is

    ``1 - 2 int |ratio(theta) - cos(theta/2)^2| sin(theta) dtheta``.

    With this calibration, a perfect Born ratio scores 1 and the
    uninformative ratio ``1/2`` scores approximately 0.
    """

    if n_theta <= 0:
        raise ValueError("n_theta must be positive")
    if pseudocount < 0.0:
        raise ValueError("pseudocount must be nonnegative")

    data0 = theta_from_z(np.cos(np.asarray(theta0, dtype=float)))
    data1 = theta_from_z(np.cos(np.asarray(theta1, dtype=float)))
    edges = np.linspace(0.0, np.pi, n_theta + 1)
    centers = (edges[:-1] + edges[1:]) / 2.0
    dtheta = edges[1] - edges[0]

    h0, _ = np.histogram(data0, bins=edges)
    h1, _ = np.histogram(data1, bins=edges)
    total = h0 + h1
    if pseudocount > 0.0:
        ratio = (h0 + pseudocount) / (total + 2.0 * pseudocount)
    else:
        with np.errstate(divide="ignore", invalid="ignore"):
            ratio = np.where(total > 0, h0 / total, empty_value)

    born = np.cos(centers / 2.0) ** 2
    abs_error = np.abs(ratio - born)
    weights = np.sin(centers)
    similarity = 1.0 - 2.0 * float(np.sum(abs_error * weights) * dtheta)
    norm = float(np.sum(weights) * dtheta)
    mean_abs_error = float(np.sum(abs_error * weights) * dtheta / norm)

    return BornRatioResult(
        theta_centers=centers,
        ratio=ratio,
        born=born,
        counts_0=h0,
        counts_1=h1,
        similarity=similarity,
        mean_abs_error=mean_abs_error,
    )


def born_ratio_from_z(
    z0: np.ndarray,
    z1: np.ndarray,
    n_theta: int = 100,
    empty_value: float = 0.5,
    pseudocount: float = 0.0,
) -> BornRatioResult:
    """Compute the Born-ratio diagnostic from Bloch ``z`` samples."""

    return born_ratio_from_theta(
        theta_from_z(z0),
        theta_from_z(z1),
        n_theta=n_theta,
        empty_value=empty_value,
        pseudocount=pseudocount,
    )


def born_ratio_from_radii(
    radii: np.ndarray,
    n_theta: int = 100,
    empty_value: float = 0.5,
    pseudocount: float = 0.0,
) -> BornRatioResult:
    """Compute the Born-ratio diagnostic directly from ``|lambda|``."""

    theta0, theta1 = theta_pair_from_radii(radii)
    return born_ratio_from_theta(
        theta0,
        theta1,
        n_theta=n_theta,
        empty_value=empty_value,
        pseudocount=pseudocount,
    )


def hill_tail_exponent(
    radii: np.ndarray,
    tail_fraction: float = 0.1,
) -> TailEstimate:
    """
    Estimate the density exponent ``alpha`` in ``q(x) ~ x^-alpha``.

    The Hill estimator is applied to the largest ``tail_fraction`` of
    positive radii.  It estimates the survival exponent first, then
    returns ``density_exponent = survival_exponent + 1``.
    """

    if not 0.0 < tail_fraction < 1.0:
        raise ValueError("tail_fraction must lie between 0 and 1")

    x = np.sort(_clean_positive(radii))
    n = x.size
    if n < 2:
        return TailEstimate(np.nan, np.nan, np.nan, 0)

    n_tail = int(np.ceil(tail_fraction * n))
    n_tail = min(max(n_tail, 1), n - 1)
    tail = x[-n_tail:]
    xmin = float(tail[0])
    mean_log = float(np.mean(np.log(tail / xmin)))
    if mean_log <= 0.0:
        survival = np.inf
    else:
        survival = 1.0 / mean_log
    density = survival + 1.0
    return TailEstimate(density, survival, xmin, n_tail)


def reciprocity_error_from_radii(
    radii: np.ndarray,
    n_log_bins: int = 40,
    min_count: int = 1,
    u_max: float | None = None,
) -> float:
    r"""
    Score the reciprocal envelope condition behind the Born ratio.

    For ``x = exp(u)``, the analytic matched-field mechanism predicts a
    core density

    ``q(x) = W(u) / (1 + x^2)^2`` with ``W(u) ~= W(-u)``.

    This function estimates ``W`` from a log-radius histogram and returns
    the mean absolute log-asymmetry ``|log W(u) - log W(-u)|``.  Smaller
    values are better.  ``nan`` is returned when there are too few
    populated mirror bins.
    """

    if n_log_bins <= 1:
        raise ValueError("n_log_bins must be greater than 1")
    if min_count < 1:
        raise ValueError("min_count must be positive")

    x = _clean_positive(radii)
    if x.size < 2:
        return np.nan

    u = np.log(x)
    if u_max is None:
        u_max = float(np.percentile(np.abs(u), 99.5))
    if not np.isfinite(u_max) or u_max <= 0.0:
        return np.nan

    edges = np.linspace(-u_max, u_max, n_log_bins + 1)
    counts, _ = np.histogram(u, bins=edges)
    widths = np.diff(edges)
    centers = (edges[:-1] + edges[1:]) / 2.0

    total = counts.sum()
    if total == 0:
        return np.nan

    p_u = counts / (total * widths)
    x_centers = np.exp(centers)
    envelope = p_u * (1.0 + x_centers**2) ** 2 / x_centers

    errors: list[float] = []
    for i in range(n_log_bins // 2):
        j = n_log_bins - 1 - i
        if counts[i] < min_count or counts[j] < min_count:
            continue
        if envelope[i] <= 0.0 or envelope[j] <= 0.0:
            continue
        errors.append(abs(float(np.log(envelope[i] / envelope[j]))))

    if not errors:
        return np.nan
    return float(np.mean(errors))


def diagnostics_from_radii(
    radii: np.ndarray,
    n_theta: int = 100,
    tail_fraction: float = 0.1,
    n_log_bins: int = 40,
) -> BornDiagnostics:
    """Return scalar diagnostics from ``|lambda|`` samples."""

    x = _clean_positive(radii, allow_zero=True)
    ratio = born_ratio_from_radii(x, n_theta=n_theta)
    tail = hill_tail_exponent(x, tail_fraction=tail_fraction)
    reciprocity = reciprocity_error_from_radii(x, n_log_bins=n_log_bins)
    positive = _clean_positive(x)

    if positive.size:
        p95 = float(np.percentile(positive, 95))
        p99 = float(np.percentile(positive, 99))
        max_radius = float(np.max(positive))
    else:
        p95 = p99 = max_radius = np.nan

    return BornDiagnostics(
        n_samples=int(x.size),
        born_similarity=ratio.similarity,
        mean_abs_ratio_error=ratio.mean_abs_error,
        reciprocity_error=reciprocity,
        tail_density_exponent=tail.density_exponent,
        tail_survival_exponent=tail.survival_exponent,
        tail_xmin=tail.xmin,
        p95_radius=p95,
        p99_radius=p99,
        max_radius=max_radius,
    )


def diagnostics_from_analyzer(
    analyzer,
    n_theta: int = 100,
    tail_fraction: float = 0.1,
    n_log_bins: int = 40,
) -> BornDiagnostics:
    """Return scalar diagnostics from a ``DisentanglementAnalyzer``."""

    if analyzer.D0 is None:
        analyzer.diagonalize_subblocks_product()
    return diagnostics_from_radii(
        np.abs(analyzer.D0),
        n_theta=n_theta,
        tail_fraction=tail_fraction,
        n_log_bins=n_log_bins,
    )


def _clean_positive(values: np.ndarray, allow_zero: bool = False) -> np.ndarray:
    arr = np.asarray(values, dtype=float).ravel()
    arr = arr[np.isfinite(arr)]
    if allow_zero:
        return arr[arr >= 0.0]
    return arr[arr > 0.0]
